### ISSUE TITLE
Gem seems to be unpublished 0.1.2 != 0.2.0

### ISSUE THREAD

**Issue by magrinj** [stereodenis/fastlane-plugin-bugsnag_sourcemaps_upload#5]
When this module is installed with the following command: `fastlane add_plugin bugsnag_sourcemaps_upload` the version downloaded is `0.1.2` instead of `0.2.0`.
Can you please publish the gem update.

A temporary fix can be editing your `Pluginfile` with:

```
gem 'fastlane-plugin-bugsnag_sourcemaps_upload', git: 'https://github.com/stereodenis/fastlane-plugin-bugsnag_sourcemaps_upload.git'
```

**Comment by stereodenis** [comment]
@magrinj 
![image](https://user-images.githubusercontent.com/1406461/98054660-a0429d00-1e4c-11eb-8481-83319186a649.png)

**Comment by magrinj** [comment]
@stereodenis Thanks for the answer !
Really strange to me, I just ran again the command and now the `0.2.0` is installed instead of the `0.1.2`...
I ran this command multiple times before creating the issues, and the old one was alway installed in October 🤔
Maybe the gem repo was not up to date or sync on my computer, sorry for the convenient !
